### ISSUE TITLE
Docs are wrong.

### ISSUE THREAD

**Issue by edlerd** [browserstack/browserstack-local-php#18]
It should say php composer.phar require browserstack/browserstack-local instead of php composer.phar require browserstack/local:dev-master

**Comment by ghost** [comment]
yes, please. 

Package on packagist.org linked to this repo is https://packagist.org/packages/browserstack/browserstack-local

**Comment by alexconrad** [comment]
Thanks ^^^ for the info. It's another "yes, please" from me, even if it's 2 years later ...
